In [38]:
import numpy as np
Employee=np.array([[1000,"Torbati","Yolanda","F","Programmer"],
                  [1001,"Kleinn","Joel","M","Programmer"],
                  [1002,"Grinsburg","Laura","F","President"],
                  [1003,"Cox","Jennifer","F","Programmer"],
                  [1005,"Ziada","Mauri","M","Product Designer"],
                  [1006,"Keyser","Cara","F","Account Executive"],
                  [1010,"Smith","Roxie","M","Programmer"],
                  [1011,"Nelson","Robert","M","Programmer"],
                  [1012,"Sachsen","Lars","M","Support Technician"],
                  [1003,"Shannon","Don","M","Product Designer"]])
#1.  How many Male employees are in a company?
print("Number of male Employees are",len(Employee[Employee[:,3]=="M"]))
#2. Display the details of employees whose Last_Name starts with S.
print(Employee[np.where(Employee[:,1]=="Sachsen")])
#3. Sort the Female Employee details in descending order based on First_Name.
Female_Employee=Employee[Employee[:,3]=="F"]
Female_Employee=Female_Employee[np.lexsort((Female_Employee[:,2],))]
print("Female Employee details in descending order based on First_Name")
print(Female_Employee)
#4. Extract 1D array and reshape it into 2D array.
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("1D array")
print(a)
b=np.array(a).reshape(3,4)
print("Reshaped 1D array into 2D array")
print(b)
#5. Extract the below matrix using Boolean and Fancy indexing.
print("Extracted Matrix")
print(Employee[[2,1],[0,1]])


Number of male Employees are 6
[['1012' 'Sachsen' 'Lars' 'M' 'Support Technician']]
Female Employee details in descending order based on First_Name
[['1006' 'Keyser' 'Cara' 'F' 'Account Executive']
 ['1003' 'Cox' 'Jennifer' 'F' 'Programmer']
 ['1002' 'Grinsburg' 'Laura' 'F' 'President']
 ['1000' 'Torbati' 'Yolanda' 'F' 'Programmer']]
1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 1D array into 2D array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Extracted Matrix
['1002' 'Kleinn']
