Numpy


In [5]:
import numpy as np
Arr=np.array([1,2,3,4,5])
print(Arr)
print(len(Arr))

[1 2 3 4 5]
5


In [6]:
rand=np.random.RandomState(52)
x=rand.randint(100,size=10)
print(x)

[28 11 13 23 86 28 32 69 11 91]


In [8]:
[x[3],x[7],x[2]]
ind=[3,7,4]
x[ind]


array([23, 69, 86])

In [10]:
ind=np.array([[1,2,3],
             [4,5,6]])
print(ind)

[[1 2 3]
 [4 5 6]]


In [13]:
print(ind)
print(x[ind])

[3, 7, 4]
[23 69 86]


In [20]:
x2=np.array([[1,2,3],[11,22,33]]) #MxN/NxM
print(x2)
print(x2.ndim) #dimension of the arry
print("Each item contains ",x2.itemsize," bytes")# size of each element
print("Array Size: ",x2.size) # number of elements in the array
print("Shape: ",x2.shape) # shape of th arrya 2x4 or 3x2
print("Each item is of the type ",x2.dtype) # datatype

[[ 1  2  3]
 [11 22 33]]
2
Each item contains  4  bytes
Array Size:  6
Shape:  (2, 3)
Each item is of the type  int32


In [23]:
print(np.add.reduce(x2)) #column sum
print("\n")
print(sum(x2)) # column sum
print("\n")
print(np.sum(x2)) # sum of all elements in the array

[12 24 36]


[12 24 36]


72


In [31]:
a=np.array([[1,2],[3,4],[5,6]])
print("Printing the original array:")
print(a)
print("Printing the array in reshape:")
print(a.reshape(2,3)) #6- 2x3 / 3x2

Printing the original array:
[[1 2]
 [3 4]
 [5 6]]
Printing the array in reshape:
[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.arange(12) # 12- 2x6, 6x2, 3x4, 4x3, 12x1, 1x12
print(a)
a=np.arange(12).reshape(3,4)
print(a)
print(a[2])
print(a[1,[2,0,3]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[6 4 7]


In [51]:
x=a[1,[1,2]]
y=a[2,[1,2]]
submat_a=np.array([x,y])
print(submat_a)

[[ 5  6]
 [ 9 10]]


In [56]:
print("The array is:\n",a) #array
print("\n The maximum element: ",a.max()) #max value in an array
print("\n The minumum element: ",a.min())  #minimum value in the array
print("\n The sum of all the element: ",a.sum()) #sum of all the numbers sum(a), a.sum()
print("\n The maximum element of column : ",a.max(axis=0)) # maximum row=1
print("\n The miniumum element of row : ",a.min(axis=1)) #minimum column=0
print("\n The Row sum: ",a.sum(axis=1)) #row sum
print("\n The Column sum: ",a.sum(axis=0)) #column sum
print("\n The square root of Array elements: \n",np.sqrt(a)) # sruare root of all numbers
print("\n The standard deviation of Array elements \n",np.std(a)) #standard deviation of each number
print("\n The Average of array is: ",np.average(a)) # avergae of the array

The array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 The maximum element:  11

 The minumum element:  0

 The sum of all the element:  66

 The maximum element of column :  [ 8  9 10 11]

 The miniumum element of row :  [0 4 8]

 The Row sum:  [ 6 22 38]

 The Column sum:  [12 15 18 21]

 The square root of Array elements: 
 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]

 The standard deviation of Array elements 
 3.452052529534663

 The Average of array is:  5.5


Arithematic operation on 2d array

In [58]:
a=np.array([[1,2,30],[10,15,4]])
print("Array a: \n",a)
b=np.array([[1,2,3],[12,19,29]])
print("Array b: \n",b)
print("Sum of the Matrices:\n",a+b)
print("product of the Matrices:\n",a*b) # incorrent multiplication due to MxN == NxM
print("Division of array a and b: \n",a/b)
print("scalar multiplication of a and b: \n",a*3)



Array a: 
 [[ 1  2 30]
 [10 15  4]]
Array b: 
 [[ 1  2  3]
 [12 19 29]]
product of the Matrices:
 [[  1   4  90]
 [120 285 116]]
Division of array a and b: 
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]
scalar multiplication of a and b: 
 [[ 3  6 90]
 [30 45 12]]


Concatenate arrays

In [59]:
print("Array a\n {} \n Array b\n {}".format(a,b))
print("Arrays vertically concatenated\n",np.vstack((a,b)))
print("Arrays horizontal concatenated\n",np.hstack((a,b)))

Array a
 [[ 1  2 30]
 [10 15  4]] 
 Array b
 [[ 1  2  3]
 [12 19 29]]
Arrays vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Arrays horizontal concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]
